# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_1', models.FileField(upload_to='picture1')),
                ('picture_2', models.FileField(upload_to='picture2')),
            ],
        ),
    ]
